source :rubygems

gem "rails", "3.0.3"
gem "ancestry"
gem "paperclip"
gem "geokit"
gem "geokit-rails3"
gem "moonshado-sms"
gem "aws-s3"
gem "jquery-rails"
gem "pg"
gem "active_device"
gem "thin", :group => :development
gem "delocalize"
gem "home_run"
gem "dynamic_form"
gem "devise", "1.2.rc"
gem "cancan"
gem "oa-oauth", :require => "omniauth/oauth"
gem "phone"